version: '3.10'

services:
  rag-api:
    build: ./RAG_API  # RAG API's Dockerfile path
    ports:
      - "8000:8000"  # Expose RAG API on port 5000
    networks:
      - app-network  # Use a custom network to allow communication between containers

  rag-frontend:
    build: ./RAG_Frontend  # Streamlit app's Dockerfile path
    ports:
      - "8501:8501"  # Expose Streamlit app on port 8501
    depends_on:
      - rag-api  # Make sure RAG API starts first
    networks:
      - app-network  # Same network to allow communication

networks:
  app-network:
    driver: bridge  # Default network driver, allows containers to communicate
